#!/bin/bash

# sync_env_manager.sh
# Synchronizes EnvManager implementation to target Package.swift files
#
# Usage: ./sync_env_manager.sh <target_directory>
# Example: ./sync_env_manager.sh ../OpenAttributeGraph

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_FILE="$SCRIPT_DIR/../Templates/EnvManager.swift.template"
START_MARKER="/* GENERATED BY SPMManifestTool. DO NOT EDIT */"
END_MARKER="/* END GENERATED BY SPMManifestTool */"

# Check if target directory is provided
if [ -z "$1" ]; then
    echo "Error: Target directory not specified"
    echo "Usage: $0 <target_directory>"
    echo "Example: $0 ../OpenAttributeGraph"
    exit 1
fi

TARGET_DIR="$1"
TARGET_FILE="$TARGET_DIR/Package.swift"

# Check if target directory exists
if [ ! -d "$TARGET_DIR" ]; then
    echo "Error: Target directory does not exist: $TARGET_DIR"
    exit 1
fi

# Check if target Package.swift exists
if [ ! -f "$TARGET_FILE" ]; then
    echo "Error: Package.swift not found in target directory: $TARGET_FILE"
    exit 1
fi

# Check if template file exists
if [ ! -f "$TEMPLATE_FILE" ]; then
    echo "Error: Template file not found: $TEMPLATE_FILE"
    exit 1
fi

# Check if markers exist in target file
if ! grep -qF "$START_MARKER" "$TARGET_FILE"; then
    echo "Error: Start marker not found in $TARGET_FILE"
    echo "Please add the following markers to your Package.swift:"
    echo "  $START_MARKER"
    echo "  $END_MARKER"
    exit 1
fi

if ! grep -qF "$END_MARKER" "$TARGET_FILE"; then
    echo "Error: End marker not found in $TARGET_FILE"
    echo "Please add the following markers to your Package.swift:"
    echo "  $START_MARKER"
    echo "  $END_MARKER"
    exit 1
fi

# Create temporary files
TEMP_FILE=$(mktemp)
TEMP_BEFORE=$(mktemp)
TEMP_AFTER=$(mktemp)

# Get line numbers of markers
START_LINE=$(grep -nF "$START_MARKER" "$TARGET_FILE" | cut -d: -f1)
END_LINE=$(grep -nF "$END_MARKER" "$TARGET_FILE" | cut -d: -f1)

# Extract content before and including start marker
sed -n "1,${START_LINE}p" "$TARGET_FILE" > "$TEMP_BEFORE"

# Extract content from and including end marker to end of file
sed -n "${END_LINE},\$p" "$TARGET_FILE" > "$TEMP_AFTER"

# Combine: before + template + after
cat "$TEMP_BEFORE" > "$TEMP_FILE"
echo "" >> "$TEMP_FILE"
cat "$TEMPLATE_FILE" >> "$TEMP_FILE"
echo "" >> "$TEMP_FILE"
cat "$TEMP_AFTER" >> "$TEMP_FILE"

# Replace target file
mv "$TEMP_FILE" "$TARGET_FILE"

# Clean up temporary files
rm -f "$TEMP_BEFORE" "$TEMP_AFTER"

echo "✅ Successfully synchronized EnvManager to $TARGET_FILE"
