#!/bin/bash

# sync_env_manager.sh
# Synchronizes EnvManager implementation to target Package.swift files
#
# Usage: ./sync_env_manager.sh <target_directory>
# Example: ./sync_env_manager.sh ../OpenAttributeGraph

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_FILE="$SCRIPT_DIR/../Sources/SPMManifestTool/EnvManager.swift"
START_MARKER="/* GENERATED BY SPMManifestTool BEGIN */"
DO_NOT_EDIT_MARKER="/* DO NOT EDIT */"
END_MARKER="/* GENERATED BY SPMManifestTool END */"

# Check if target directory is provided
if [ -z "$1" ]; then
    echo "Error: Target directory not specified"
    echo "Usage: $0 <target_directory>"
    echo "Example: $0 ../OpenAttributeGraph"
    exit 1
fi

TARGET_DIR="$1"
TARGET_FILE="$TARGET_DIR/Package.swift"

# Check if target directory exists
if [ ! -d "$TARGET_DIR" ]; then
    echo "Error: Target directory does not exist: $TARGET_DIR"
    exit 1
fi

# Check if target Package.swift exists
if [ ! -f "$TARGET_FILE" ]; then
    echo "Error: Package.swift not found in target directory: $TARGET_FILE"
    exit 1
fi

# Check if source file exists
if [ ! -f "$SOURCE_FILE" ]; then
    echo "Error: Source file not found: $SOURCE_FILE"
    exit 1
fi

# Check if markers exist in target file
if ! grep -qF "$START_MARKER" "$TARGET_FILE"; then
    echo "Error: Start marker not found in $TARGET_FILE"
    echo "Please add the following markers to your Package.swift:"
    echo "  $START_MARKER"
    echo "  $DO_NOT_EDIT_MARKER"
    echo "  $END_MARKER"
    exit 1
fi

if ! grep -qF "$END_MARKER" "$TARGET_FILE"; then
    echo "Error: End marker not found in $TARGET_FILE"
    echo "Please add the following markers to your Package.swift:"
    echo "  $START_MARKER"
    echo "  $DO_NOT_EDIT_MARKER"
    echo "  $END_MARKER"
    exit 1
fi

# Create temporary files
TEMP_FILE=$(mktemp)
TEMP_BEFORE=$(mktemp)
TEMP_AFTER=$(mktemp)
TEMP_CONTENT=$(mktemp)

# Get line numbers of markers
START_LINE=$(grep -nF "$START_MARKER" "$TARGET_FILE" | cut -d: -f1)
END_LINE=$(grep -nF "$END_MARKER" "$TARGET_FILE" | cut -d: -f1)

# Extract content before and including start marker
sed -n "1,${START_LINE}p" "$TARGET_FILE" > "$TEMP_BEFORE"

# Extract content from and including end marker to end of file
sed -n "${END_LINE},\$p" "$TARGET_FILE" > "$TEMP_AFTER"

# Process EnvManager.swift content:
# 1. Remove #if canImport(PackageDescription)'s else branch and the if/endif directives
# 2. Keep only the if-branch code (PackageDescription branch)
# 3. Keep all other content as-is (public, nonisolated(unsafe), etc.)
awk '
    BEGIN {
        if_stack[0] = 0
        stack_depth = 0
        skip = 0
    }

    # Handle #if canImport(PackageDescription) - enter conditional block, keep if branch
    /^[ \t]*#if canImport\(PackageDescription\)/ {
        stack_depth++
        if_stack[stack_depth] = 1  # Mark as in if-branch
        next
    }

    # Handle #else - switch to else branch, start skipping
    /^[ \t]*#else$/ {
        if (stack_depth > 0 && if_stack[stack_depth] == 1) {
            if_stack[stack_depth] = 2  # Mark as in else-branch (skip)
        }
        next
    }

    # Handle #endif - exit conditional block
    /^[ \t]*#endif$/ {
        if (stack_depth > 0) {
            stack_depth--
        }
        next
    }

    # Skip lines when in else-branch
    {
        skip = 0
        for (i = 1; i <= stack_depth; i++) {
            if (if_stack[i] == 2) {
                skip = 1
                break
            }
        }
        if (!skip) {
            print
        }
    }
' "$SOURCE_FILE" > "$TEMP_CONTENT"

# Combine: before + DO NOT EDIT marker + blank + content + blank + after
cat "$TEMP_BEFORE" > "$TEMP_FILE"
echo "$DO_NOT_EDIT_MARKER" >> "$TEMP_FILE"
echo "" >> "$TEMP_FILE"
cat "$TEMP_CONTENT" >> "$TEMP_FILE"
echo "" >> "$TEMP_FILE"
cat "$TEMP_AFTER" >> "$TEMP_FILE"

# Replace target file
mv "$TEMP_FILE" "$TARGET_FILE"

# Clean up temporary files
rm -f "$TEMP_BEFORE" "$TEMP_AFTER" "$TEMP_CONTENT"

echo "✅ Successfully synchronized EnvManager to $TARGET_FILE"
